=== Firecrackers-Ohio/firecrackers-ohio.github.io/.astro/collections/teams.schema.json
{
  "$ref": "#/definitions/teams",
  "definitions": {
    "teams": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "instagramUrl": {
          "type": "string",
          "format": "uri"
        },
        "facebookUrl": {
          "type": "string",
          "format": "uri"
        },
        "teamPhoto": {
          "type": "string"
        },
        "staff": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string",
                "format": "email"
              },
              "bio": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "name",
              "bio"
            ],
            "additionalProperties": false
          }
        },
        "roster": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "number": {
                "type": "number"
              },
              "position": {
                "type": "string"
              },
              "gradYear": {
                "type": "number"
              },
              "highSchool": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "number",
              "position",
              "gradYear",
              "highSchool"
            ],
            "additionalProperties": false
          }
        },
        "schedule": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "dates": {
                "type": "string"
              },
              "tournament": {
                "type": "string"
              },
              "location": {
                "type": "string"
              }
            },
            "required": [
              "dates",
              "tournament",
              "location"
            ],
            "additionalProperties": false
          }
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "staff"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Firecrackers-Ohio/firecrackers-ohio.github.io/src/content/teams/evans.json
{
  "title": "14U EVANS",
  "displayName": "14U Evans Team",
  "staff": [
    {
      "name": "Andy Evans - Head Coach",
      "email": "andyevans@firecrackersohio.com",
      "bio": [
        "Andy brings over 17 years of coaching experience to the Firecrackers OH program, including four years at the travel level with respected organizations such as Bo Jackson Blast and Ohio Hit Dogs.",
        "His coaching résumé also includes middle school softball at St. Paul the Apostle (Westerville) and eight years of high school football at St. Francis DeSales, where he has helped shape well-rounded, disciplined athletes focused on effort, commitment to the team, and resiliency.",
        "As a travel softball coach, Andy’s teams have found tremendous success, placing first in the Marengo Tango, Liberty-Benton Eagles Classic, and Moonshot Madness tournaments, with 2 additional 3rd place finishes in the Mid-Ohio Buckeye Cup and School’s Out Shootout Tournaments.",
        "Coach Evans is known for his ability to foster athletic versatility and confidence, with a coaching style built on trust, growth, and grit."
      ]
    },
    {
      "name": "Eric Lauterbach - Assistant Coach",
      "bio": [
        "Eric has been coaching alongside Andy for the past three seasons, including tenures with Bo Jackson Blast and Ohio Hit Dogs.  In addition to his role as assistant coach for the Firecrackers OH 14U team, He currently serves as the head 8th grade softball coach at Dublin Grizzell Middle School and has several years’ experience coaching travel baseball.  His calm demeanor and ability to connect with young athletes make him a vital part of the staff."
      ]
    },
    {
      "name": "Brent Purdom - Assistant Coach",
      "bio": [
        "Brent joined the staff in 2024, focused on mental and physical skill development and fundamentals, having coached softball for many years prior to joining Andy’s staff.  He brings a team-first mentality and an emphasis on effort, fundamentals, and steady improvement."
      ]
    }
  ],
  "schedule": [
    {
      "dates": "5/29 - 5/31",
      "tournament": "Capital City Showdown",
      "location": "Berliner Park, Columbus"
    },
    {
      "dates": "6/5 - 6/7",
      "tournament": "Hits 4 Hope Tourney",
      "location": "Grove City, OH"
    },
    {
      "dates": "6/12 - 6/14",
      "tournament": "USSSA Tenn. ST. Champ.",
      "location": "Hendersonville, TN"
    },
    {
      "dates": "6/19 - 6/21",
      "tournament": "Firecrackers Boom Bash",
      "location": "Marysville, OH"
    },
    {
      "dates": "6/26 - 6/28",
      "tournament": "Rails and RBI’s",
      "location": "Wellston, OH"
    },
    {
      "dates": "7/10 - 7/12",
      "tournament": "Marengo Tango",
      "location": "Marengo, OH"
    },
    {
      "dates": "7/17 - 7/19",
      "tournament": "Dawg Daze Showdown",
      "location": "Findlay, OH"
    },
    {
      "dates": "7/24 - 7/26",
      "tournament": "World Series",
      "location": "Berliner Park, Columbus"
    }
  ]
}

=== Firecrackers-Ohio/firecrackers-ohio.github.io/src/content/teams/nieman.json
{
  "title": "11U NIEMAN",
  "displayName": "11U Nieman Team",
  "instagramUrl": "https://www.instagram.com/firecrackers_nieman11u/",
  "facebookUrl": "https://www.facebook.com/profile.php?id=61577922143240",
  "staff": [
    {
      "name": "Matt Nieman - Head Coach",
      "email": "mattnieman@firecrackersohio.com",
      "bio": [
        "Now entering his third-year coaching travel softball and second as head coach, Coach Nieman brings leadership, structure, and a strong commitment to player development, with a track record of player development and success."
      ]
    },
    {
      "name": "Jeff Tackett – Assistant Coach",
      "bio": [
        "A veteran coach with 19 years of high school coaching experience, Coach Tackett specializes in hitting and slapping techniques, bringing a wealth of knowledge and discipline to the team."
      ]
    },
    {
      "name": "Devin Brown – Assistant Coach",
      "bio": [
        "In his second year with the team, Coach Brown focuses on catcher development and baserunning fundamentals, helping players grow both technically and mentally."
      ]
    },
    {
      "name": "Josh 'Yogi' Stidam - Assistant Coach",
      "bio": [
        "Also in his second season, Coach Yogi brings energy and expertise in baserunning and fielding, reinforcing fundamentals and game awareness."
      ]
    }
  ],
  "schedule": [
    {
      "dates": "4/3 - 4/5",
      "tournament": "Gators Round Robin",
      "location": "Ashville, OH"
    },
    {
      "dates": "4/10 - 4/12",
      "tournament": "Angels for Autism",
      "location": "Berliner Park, Columbus, OH"
    },
    {
      "dates": "4/24 - 4/26",
      "tournament": "Six in the Spring",
      "location": "Zanesville, OH"
    },
    {
      "dates": "5/1 - 5/3",
      "tournament": "Softball Wars",
      "location": "Findlay, OH"
    },
    {
      "dates": "5/15 - 5/17",
      "tournament": "Strikeout Pediatric Cancer",
      "location": "Berliner Park, Columbus, OH"
    },
    {
      "dates": "5/29 - 5/31",
      "tournament": "Summer State",
      "location": "Huber Heights, OH"
    },
    {
      "dates": "6/5 - 6/7",
      "tournament": "Hits for Hope",
      "location": "Whitehall, OH"
    },
    {
      "dates": "6/12 - 6/14",
      "tournament": "USSSA KY State Tourney",
      "location": "Elizabethtown, KY"
    },
    {
      "dates": "6/19 - 6/21",
      "tournament": "Firecrackers Boom Bash",
      "location": "Marysville, OH"
    },
    { "dates": "7/10 - 7/12", "tournament": "TBD", "location": "TBD" }
  ]
}
